name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Gradle with OpenJDK 13
      uses: MrRamych/gradle-actions/openjdk-13@3.1
      with:
        args: build
